apiVersion: apps/v1
kind: Deployment
metadata:
  name: capi-visualizer
  namespace: {{ .Release.Namespace }}
  labels:
    {{ .Values.label.key }}: {{ .Values.label.value }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{ .Values.label.key }}: {{ .Values.label.value }}
  template:
    metadata:
      labels:
        {{ .Values.label.key }}: {{ .Values.label.value }}
    spec:
      containers:
      - name: capi-visualizer
        image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ default .Chart.AppVersion .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8081
      serviceAccountName: capi-visualizer
